baseURL = ""
title = "Scott McKenzie"
theme = "manis-hugo-theme"

pluralizeListTitles = false

# Minimum number of posts before paginate navigation show up
paginate = 10

# Your disqus shortname
disqusShortname = ""

# Edit this if you want to translate your blog
defaultContentLanguage = "en"

# Code Highlighting (Chroma)
pygmentsCodeFences = true
pygmentsUseClasses = true

[menu]
[[menu.main]]
name = "Posts"
url = "/post/"

[[menu.main]]
name = "About"
url = "/about"

[taxonomies]
tag = "tags"

[params]
# If false, use minified CSS (ui.min.css)
debugCSS = false
# Custom CSS
customCSS = ["/reactable.css"]

# Site meta description
description = "Data Analyst Blog."
# Site's Tagline (Subtitle or Keyword)
tagline = "Illuminating Analytics"
# If true give attribution to this theme
themeAttrib = true
# URL to license file, can be outside of your domain
licenseURL = "/about/license"

# Configure which sections for Latest Posts
mainSections = ["blog", "post"]
# Configure which sections for Latest Works
workSections = ["work"]

# List of sections that support disqus comments
disqusSections = [ "blog" ]
# List of sections that support utterances comments
utterancesSections = [ "blog" ]

# Utterances Configuration
utterancesRepo = ""
utterancesTheme = "github-light"
utterancesLabel = ""

# 404 Configuration
head404 = "Sorry, I can't find what you want."
sub404 = "Back to <a href='/'>Home</a>."

# Color of your website's accent
colorTheme = "#ff830c"
# Maximum number of item in Latest Posts or Works
latestCount = 3
# Path to site's favicon image
faviconImg = "/globe.svg"
# Date format in item list
dateFmt = "Jan 02, 2006"

# Code Highlighting (HighlightJS)
highlightJs = true
highlightJsLanguages = [ "go", "r" ]
highlightJsStyle = "zenburn"

# Social Links
twitter = "https://twitter.com/sccmckenzie"
github = "https://github.com/sccmckenzie"

[markup.goldmark.renderer]
  unsafe = true